services:
  - type: web
    name: medi-tracker
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    domains:
      - ivm.duniyahealthcare.com
    renderSubdomainPolicy: disabled
    envVars:
      - key: PORT
        value: "8080"
      - key: RESEND_API_KEY
        sync: false
